# ---------------------------------------------------------------------------
# Starting Title
# ---------------------------------------------------------------------------

# Enable starting title.
# Default: False
EnableStartingTitle = True

# Starting title for new players.
StartingTitle = NoobMeinster
